COLUMNS:
  Company: str
  TypeName: str
  Inches: float64
  ScreenResolution: str
  Cpu: str
  Ram: str
  Memory: str
  Gpu: str
  OpSys: str
  Weight: str
  Price: float64

TARGET_NAME:
  Price: float64